import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { config } from "dotenv";

config({ path: ".env.local", quiet: true });

// Snapshots the seeded support_desk data into db/seed.sql so it can be loaded with plain SQL
// (e.g. the Supabase SQL editor). Timestamps become offsets from now() so SLA states stay realistic.
const TABLES = ["users", "tickets", "comments", "ticket_events", "notifications"] as const;

function literal(v: unknown, ref: number, col: string): string {
  if (v === null || v === undefined) return "NULL";
  if (col === "needed_by") {
    const today = Date.parse(new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata" }).format(ref));
    const days = Math.round((Date.parse(String(v)) - today) / 86_400_000);
    return `(now() AT TIME ZONE 'Asia/Kolkata')::date + ${days}`;
  }
  if (v instanceof Date) return `now() - interval '${Math.round((ref - v.getTime()) / 1000)} seconds'`;
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
}

async function main() {
  const { sql, closeDb } = await import("../src/lib/db");
  const ref = Date.now();
  const out: string[] = [
    "-- Generated by `npm run db:export-sql` from the replayed seed (db/seed.ts). Run after db/schema.sql.",
    "BEGIN;",
    "TRUNCATE support_desk.notifications, support_desk.ticket_events, support_desk.comments, support_desk.tickets, support_desk.users RESTART IDENTITY CASCADE;",
  ];
  try {
    for (const table of TABLES) {
      const rows = await sql.unsafe(`SELECT * FROM support_desk.${table} ORDER BY id`);
      if (!rows.length) continue;
      const cols = Object.keys(rows[0]).map((c) => c.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`));
      const values = rows.map((r) => `  (${Object.values(r).map((v, i) => literal(v, ref, cols[i])).join(", ")})`);
      out.push(`INSERT INTO support_desk.${table} (${cols.join(", ")}) VALUES\n${values.join(",\n")};`);
      out.push(`SELECT setval(pg_get_serial_sequence('support_desk.${table}', 'id'), (SELECT max(id) FROM support_desk.${table}));`);
    }
    out.push("COMMIT;", "");
    writeFileSync(join(__dirname, "seed.sql"), out.join("\n\n"));
    console.log("Wrote db/seed.sql");
  } finally {
    await closeDb();
  }
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
